apiVersion: v1
kind: Pod
metadata:
  name: ganeshnginx2
  labels: 
    app: ganenginx
spec:
 containers:
   - name: nginxcontainer1
     image: nginx
     
---

apiVersion: v1
kind: Service
metadata:
  name: nginxservice2
spec:
  ports:
      port: 80
  selector:
    app: ganengnix

